@startuml hamburgueseria
left to right direction
' definición de actores
together {
    actor Cajera
    actor CajeraTelefónica
    Cajera <|- CajeraTelefónica
}
together {
    actor Repartidor
    actor Cocinero
}
together {
    actor Administrador
    actor Contable
}
' caja del sistema
rectangle {
    ' casos de uso básicos
    Cajera --> (crear pedido)
    Cajera --> (consultar pedido)
    Cajera --> (cobrar)
    Cajera --> (cerrar pedido)
    CajeraTelefónica --> (pedido tfno)

    Administrador --> (consultar pedido)
    Administrador --> (cambiar tarifas)

    Contable --> (arqueo)
    Contable --> (comparativa)
    Contable --> (generar informe)

    ' si invierto el orden los actores se colocan en otra posición
    (repartos pendientes) <-- Repartidor
    (en reparto) <-- Repartidor
    (entregado) <-- Repartidor

    (actualizar pedido) <-- Cocinero

    ' extends
    (pedido tfno) .> (crear pedido) : "extends"
    ' includes
    (crear pedido) ..> (asignar repartidor): "includes"
    (crear pedido) ..> (recuperar menú): "includes"
    (crear pedido) ..> (recuperar complementos): "includes"
    (crear pedido) ..> (enviar a cocina): "includes"
}
@enduml